
version: '2.0'

services:
    Website1:
        image: ghcr.io/RohaanMooken/X:latest
        deploy:
        labels: [com.centurylinklabs.watchtower.enable=true]
        container_name: mooken
        restart: always
        ports:
            - "80:80"